Repository react-karly/react-karly-project, pull requests merged in 2023-03, with the labels that each got.

#105 [상품 리스트 페이지] Side-Menu 마크업 및 스타일, 일부 기능 구현 완료.
  src/App.jsx
  src/components/Container/Container.jsx
  src/components/Container/Container.module.css
  src/components/Kategori/Kategori.jsx
  src/components/Kategori/Kategori.module.css
  src/components/Layout/Layout.jsx
  src/components/Layout/Layout.module.css
  src/components/ListCard/ListCard.jsx
  src/components/ListCard/ListCard.module.css
  src/components/ListsideMenu/ListSideMenu.jsx
  src/components/ListsideMenu/ListSideMenu.module.css
  src/components/ListsideMenu/MenuList.js
  src/components/SubKategori/SubKategori.jsx
  src/components/SubKategori/SubKategori.module.css
  src/components/index.js
  src/css/theme.module.css
  src/main.jsx
  src/pages/ProductList/ProductList.jsx
  src/pages/ProductList/ProductList.module.css
  src/pages/example.jsx
Labels: feat, chore, style

#120 [상품 리스트] List-Card 마크업 및 기능 구현
  src/components/ListCard/ListCard.jsx
  src/components/ListCard/ListCard.module.css
  src/components/ProductList/Kategori/Kategori.jsx
  src/components/ProductList/Kategori/Kategori.module.css
  src/components/ProductList/ListCard/ListCard.jsx
  src/components/ProductList/ListCard/ListCard.module.css
  src/components/ProductList/ListCards/ListCards.jsx
  src/components/ProductList/ListCards/ListCards.module.css
  src/components/ProductList/ListCards/ListFilter.js
  src/components/ProductList/ListFilter/ListFilter.jsx
  src/components/ProductList/ListFilter/ListFilter.module.css
  src/components/ProductList/ListsideMenu/ListSideMenu.jsx
  src/components/ProductList/ListsideMenu/ListSideMenu.module.css
  src/components/ProductList/ListsideMenu/MenuList.js
  src/components/ProductList/SubKategori/SubKategori.jsx
  src/components/ProductList/SubKategori/SubKategori.module.css
  src/components/index.js
  src/pages/ProductList/ProductList.jsx
  src/pages/ProductList/ProductList.module.css
Labels: feat, chore, style

#129 Develop
  index.html
  src/assets/logo.svg
  src/components/ProductList/CartModal/CartModal.jsx
  src/components/ProductList/CartModal/CartModal.module.css
  src/components/ProductList/ListCard/ListCard.jsx
  src/components/ProductList/ListsideMenu/ListSideMenu.module.css
  src/pages/ProductList/ProductList.jsx
Labels: feat, chore, style

#136 [로그인, 회원가입] 로그인, 회원가입 마크업 CSS 완성 및 일부 기능 구현 #9 #36 #37 #45 #47 #48 #50 #85 #86
  package-lock.json
  package.json
  src/App.jsx
  src/atoms/auth.js
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
  src/components/LoginModal/LoginModal.jsx
  src/components/LoginModal/LoginModal.module.css
  src/components/Register/Address.jsx
  src/components/Register/Address.module.css
  src/components/Register/BirthdayInput.jsx
  src/components/Register/BirthdayInput.module.css
  src/components/Register/Btn.jsx
  src/components/Register/Btn.module.css
  src/components/Register/EventRadioBtn.jsx
  src/components/Register/EventRadioBtn.module.css
  src/components/Register/GenderRadioBtn.jsx
  src/components/Register/GenderRadioBtn.module.css
  src/components/Register/Input.jsx
  src/components/Register/Input.module.css
  src/components/Register/RegisterTOS.jsx
  src/components/Register/RegisterTOS.module.css
  src/components/Register/TermList.jsx
  src/components/Register/TermList.module.css
  src/components/Register/UserInput.jsx
  src/components/Register/UserInput.module.css
  src/components/index.jsx
  src/config/firebase.js
  src/firebase/auth/auth.js
  src/pages/Login.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/Login.module.css
  src/pages/Register.jsx
  src/pages/Register.module.css
  src/pages/Register/Register.jsx
  src/pages/Register/Register.module.css
Labels: feat, setting, chore, style

#144 [로그인/회원가입] 회원가입 유효성 검사 및 로그인 모달 리팩토링
  src/atoms/auth.js
  src/components/LoginModal/LoginModal.jsx
  src/components/Register/UserInput.jsx
  src/components/Register/UserInput.module.css
  src/pages/Login/Login.jsx
  src/pages/Register/Register.jsx
Labels: fix, feat, setting, chore, style

#157 [회원가입/로그인] 헤더와 충돌 방지를 위해 클래스명 추가
  src/components/Register/UserInput.jsx
  src/components/Register/UserInput.module.css
Labels: style
